package com.fu.social4learning.dto;
// Generated Feb 12, 2016 9:50:55 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "Comment", catalog = "social4learning")
public class Comment implements java.io.Serializable {

	private Integer id;
	private int topicId;
	private int userId;
	private int commentNumber;
	private Integer replyForComment;
	private Date createTime;
	private String content;

	public Comment() {
	}

	public Comment(int topicId, int userId, int commentNumber, Date createTime, String content) {
		this.topicId = topicId;
		this.userId = userId;
		this.commentNumber = commentNumber;
		this.createTime = createTime;
		this.content = content;
	}

	public Comment(int topicId, int userId, int commentNumber, Integer replyForComment, Date createTime,
			String content) {
		this.topicId = topicId;
		this.userId = userId;
		this.commentNumber = commentNumber;
		this.replyForComment = replyForComment;
		this.createTime = createTime;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "topicId", nullable = false)
	public int getTopicId() {
		return this.topicId;
	}

	public void setTopicId(int topicId) {
		this.topicId = topicId;
	}

	@Column(name = "userId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "commentNumber", nullable = false)
	public int getCommentNumber() {
		return this.commentNumber;
	}

	public void setCommentNumber(int commentNumber) {
		this.commentNumber = commentNumber;
	}

	@Column(name = "replyForComment")
	public Integer getReplyForComment() {
		return this.replyForComment;
	}

	public void setReplyForComment(Integer replyForComment) {
		this.replyForComment = replyForComment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createTime", nullable = false, length = 10)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
