package com.fu.social4learning.dto;
// Generated Feb 12, 2016 9:50:55 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConvParticipantId generated by hbm2java
 */
@Embeddable
public class ConvParticipantId implements java.io.Serializable {

	private int conversationId;
	private int userId;

	public ConvParticipantId() {
	}

	public ConvParticipantId(int conversationId, int userId) {
		this.conversationId = conversationId;
		this.userId = userId;
	}

	@Column(name = "conversationId", nullable = false)
	public int getConversationId() {
		return this.conversationId;
	}

	public void setConversationId(int conversationId) {
		this.conversationId = conversationId;
	}

	@Column(name = "userId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConvParticipantId))
			return false;
		ConvParticipantId castOther = (ConvParticipantId) other;

		return (this.getConversationId() == castOther.getConversationId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getConversationId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
