package com.fu.social4learning.dto;
// Generated Feb 12, 2016 9:50:55 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Friend generated by hbm2java
 */
@Entity
@Table(name = "Friend", catalog = "social4learning")
public class Friend implements java.io.Serializable {

	private FriendId id;
	private Date createDate;

	public Friend() {
	}

	public Friend(FriendId id, Date createDate) {
		this.id = id;
		this.createDate = createDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId1", column = @Column(name = "userId1", nullable = false) ),
			@AttributeOverride(name = "userId2", column = @Column(name = "userId2", nullable = false) ) })
	public FriendId getId() {
		return this.id;
	}

	public void setId(FriendId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createDate", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
