package com.fu.social4learning.dto;
// Generated Feb 12, 2016 9:50:55 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResultId generated by hbm2java
 */
@Embeddable
public class ResultId implements java.io.Serializable {

	private int testId;
	private int studentId;

	public ResultId() {
	}

	public ResultId(int testId, int studentId) {
		this.testId = testId;
		this.studentId = studentId;
	}

	@Column(name = "testId", nullable = false)
	public int getTestId() {
		return this.testId;
	}

	public void setTestId(int testId) {
		this.testId = testId;
	}

	@Column(name = "studentId", nullable = false)
	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResultId))
			return false;
		ResultId castOther = (ResultId) other;

		return (this.getTestId() == castOther.getTestId()) && (this.getStudentId() == castOther.getStudentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTestId();
		result = 37 * result + this.getStudentId();
		return result;
	}

}
