package com.fu.social4learning.dto;
// Generated Feb 12, 2016 9:50:55 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StudentChoiceAnswer generated by hbm2java
 */
@Entity
@Table(name = "StudentChoiceAnswer", catalog = "social4learning", uniqueConstraints = @UniqueConstraint(columnNames = "answerId") )
public class StudentChoiceAnswer implements java.io.Serializable {

	private StudentChoiceAnswerId id;
	private Integer answerId;

	public StudentChoiceAnswer() {
	}

	public StudentChoiceAnswer(StudentChoiceAnswerId id) {
		this.id = id;
	}

	public StudentChoiceAnswer(StudentChoiceAnswerId id, Integer answerId) {
		this.id = id;
		this.answerId = answerId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "studentId", column = @Column(name = "studentId", nullable = false) ),
			@AttributeOverride(name = "testId", column = @Column(name = "testId", nullable = false) ),
			@AttributeOverride(name = "questionId", column = @Column(name = "questionId", nullable = false) ) })
	public StudentChoiceAnswerId getId() {
		return this.id;
	}

	public void setId(StudentChoiceAnswerId id) {
		this.id = id;
	}

	@Column(name = "answerId", unique = true)
	public Integer getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(Integer answerId) {
		this.answerId = answerId;
	}

}
