package com.fu.social4learning.dto;
// Generated Feb 12, 2016 9:50:55 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StudentWriteAnswer generated by hbm2java
 */
@Entity
@Table(name = "StudentWriteAnswer", catalog = "social4learning")
public class StudentWriteAnswer implements java.io.Serializable {

	private StudentWriteAnswerId id;
	private String answer;
	private boolean isMarked;
	private Integer grade;
	private Integer assignedTeacher;
	private String comment;

	public StudentWriteAnswer() {
	}

	public StudentWriteAnswer(StudentWriteAnswerId id, boolean isMarked) {
		this.id = id;
		this.isMarked = isMarked;
	}

	public StudentWriteAnswer(StudentWriteAnswerId id, String answer, boolean isMarked, Integer grade,
			Integer assignedTeacher, String comment) {
		this.id = id;
		this.answer = answer;
		this.isMarked = isMarked;
		this.grade = grade;
		this.assignedTeacher = assignedTeacher;
		this.comment = comment;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "studentId", column = @Column(name = "studentId", nullable = false) ),
			@AttributeOverride(name = "testId", column = @Column(name = "testId", nullable = false) ),
			@AttributeOverride(name = "questionId", column = @Column(name = "questionId", nullable = false) ) })
	public StudentWriteAnswerId getId() {
		return this.id;
	}

	public void setId(StudentWriteAnswerId id) {
		this.id = id;
	}

	@Column(name = "answer", length = 65535)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "isMarked", nullable = false)
	public boolean isIsMarked() {
		return this.isMarked;
	}

	public void setIsMarked(boolean isMarked) {
		this.isMarked = isMarked;
	}

	@Column(name = "grade")
	public Integer getGrade() {
		return this.grade;
	}

	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	@Column(name = "assignedTeacher")
	public Integer getAssignedTeacher() {
		return this.assignedTeacher;
	}

	public void setAssignedTeacher(Integer assignedTeacher) {
		this.assignedTeacher = assignedTeacher;
	}

	@Column(name = "comment", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
